### ISSUE TITLE
creating.jl example chords generates xml that doesn't work with musicxml schema

### ISSUE THREAD

**Issue by malbert137** [JuliaMusic/MusicXML.jl#40]
First, thank you very much for the library, and for looking at this.

According to:
https://www.musicxml.com/tutorial/the-midi-compatible-part/chords/
the first note in a chord should *NOT* have a <chord/> tag.

I stumbled upon this when "flat.io" rejected the xml.

The following modifications seem to work:

music/music01 % diff -c creating.jl tst7.jl
*** creating.jl	2020-05-03 20:51:56.000000000 -0400
--- tst7.jl	2020-05-05 15:42:24.000000000 -0400
***************
*** 62,68 ****
  
  measure1_notes_guitar = [
  # G Major chord for a bar
! Note(pitch = Pitch(step = "G", alter = 0, octave = 2), duration =  16, chord = Chord()),
  Note(pitch = Pitch(step = "B", alter = 0, octave = 2), duration =  16, chord = Chord()),
  Note(pitch = Pitch(step = "D", alter = 0, octave = 3), duration =  16, chord = Chord()),
  Note(pitch = Pitch(step = "G", alter = 0, octave = 3), duration =  16, chord = Chord()),
--- 62,68 ----
  
  measure1_notes_guitar = [
  # G Major chord for a bar
! Note(pitch = Pitch(step = "G", alter = 0, octave = 2), duration =  16),
  Note(pitch = Pitch(step = "B", alter = 0, octave = 2), duration =  16, chord = Chord()),
  Note(pitch = Pitch(step = "D", alter = 0, octave = 3), duration =  16, chord = Chord()),
  Note(pitch = Pitch(step = "G", alter = 0, octave = 3), duration =  16, chord = Chord()),
***************
*** 72,78 ****
  
  measure2_notes_guitar = [
  # G Major chord for half a bar
! Note(pitch = Pitch(step = "G", alter = 0, octave = 2), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "B", alter = 0, octave = 2), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "D", alter = 0, octave = 3), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "G", alter = 0, octave = 3), duration =  8, chord = Chord()),
--- 72,78 ----
  
  measure2_notes_guitar = [
  # G Major chord for half a bar
! Note(pitch = Pitch(step = "G", alter = 0, octave = 2), duration =  8),
  Note(pitch = Pitch(step = "B", alter = 0, octave = 2), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "D", alter = 0, octave = 3), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "G", alter = 0, octave = 3), duration =  8, chord = Chord()),
***************
*** 80,86 ****
  Note(pitch = Pitch(step = "G", alter = 0, octave = 4), duration =  8, chord = Chord()),
  
  # G Major chord for half a bar
! Note(pitch = Pitch(step = "G", alter = 0, octave = 2), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "B", alter = 0, octave = 2), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "D", alter = 0, octave = 3), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "G", alter = 0, octave = 3), duration =  8, chord = Chord()),
--- 80,86 ----
  Note(pitch = Pitch(step = "G", alter = 0, octave = 4), duration =  8, chord = Chord()),
  
  # G Major chord for half a bar
! Note(pitch = Pitch(step = "G", alter = 0, octave = 2), duration =  8),
  Note(pitch = Pitch(step = "B", alter = 0, octave = 2), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "D", alter = 0, octave = 3), duration =  8, chord = Chord()),
  Note(pitch = Pitch(step = "G", alter = 0, octave = 3), duration =  8, chord = Chord()),
***************

**Comment by aminya** [comment]
Thanks for reporting this. The examples are fixed now. I plan to implement some intelligent tools to prevent this kind of errors.
